apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      port: 8900
      protocol: TCP
      targetPort: http
    - port: 5600
      targetPort: grpc
      protocol: TCP
      name: grpc
